PRAGMA foreign_keys=OFF;
BEGIN TRANSACTION;
CREATE TABLE IF NOT EXISTS "django_migrations" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "app" varchar(255) NOT NULL, "name" varchar(255) NOT NULL, "applied" datetime NOT NULL);
INSERT INTO django_migrations VALUES(1,'contenttypes','0001_initial','2025-03-27 18:29:08.542109');
INSERT INTO django_migrations VALUES(2,'contenttypes','0002_remove_content_type_name','2025-03-27 18:29:08.550682');
INSERT INTO django_migrations VALUES(3,'auth','0001_initial','2025-03-27 18:29:08.566541');
INSERT INTO django_migrations VALUES(4,'auth','0002_alter_permission_name_max_length','2025-03-27 18:29:08.575630');
INSERT INTO django_migrations VALUES(5,'auth','0003_alter_user_email_max_length','2025-03-27 18:29:08.581962');
INSERT INTO django_migrations VALUES(6,'auth','0004_alter_user_username_opts','2025-03-27 18:29:08.589020');
INSERT INTO django_migrations VALUES(7,'auth','0005_alter_user_last_login_null','2025-03-27 18:29:08.595878');
INSERT INTO django_migrations VALUES(8,'auth','0006_require_contenttypes_0002','2025-03-27 18:29:08.598093');
INSERT INTO django_migrations VALUES(9,'auth','0007_alter_validators_add_error_messages','2025-03-27 18:29:08.604888');
INSERT INTO django_migrations VALUES(10,'auth','0008_alter_user_username_max_length','2025-03-27 18:29:08.611631');
INSERT INTO django_migrations VALUES(11,'auth','0009_alter_user_last_name_max_length','2025-03-27 18:29:08.618266');
INSERT INTO django_migrations VALUES(12,'auth','0010_alter_group_name_max_length','2025-03-27 18:29:08.626651');
INSERT INTO django_migrations VALUES(13,'auth','0011_update_proxy_permissions','2025-03-27 18:29:08.632535');
INSERT INTO django_migrations VALUES(14,'auth','0012_alter_user_first_name_max_length','2025-03-27 18:29:08.639476');
INSERT INTO django_migrations VALUES(15,'journalapp','0001_initial','2025-03-27 18:29:08.706875');
INSERT INTO django_migrations VALUES(16,'admin','0001_initial','2025-03-27 18:29:08.724058');
INSERT INTO django_migrations VALUES(17,'admin','0002_logentry_remove_auto_add','2025-03-27 18:29:08.742554');
INSERT INTO django_migrations VALUES(18,'admin','0003_logentry_add_action_flag_choices','2025-03-27 18:29:08.758613');
INSERT INTO django_migrations VALUES(19,'journalapp','0002_rename_journal_article_and_more','2025-03-27 18:29:08.898426');
INSERT INTO django_migrations VALUES(20,'sessions','0001_initial','2025-03-27 18:29:08.903438');
INSERT INTO django_migrations VALUES(21,'journalapp','0003_alter_articlecategory_options_and_more','2025-03-28 00:03:06.948443');
INSERT INTO django_migrations VALUES(22,'journalapp','0004_article_keywords','2025-03-28 00:26:02.529625');
INSERT INTO django_migrations VALUES(23,'journalapp','0005_article_revised_document_article_revision_notes_and_more','2025-03-30 21:43:33.000584');
INSERT INTO django_migrations VALUES(24,'journalapp','0006_archivedjournal','2025-03-30 23:10:23.170543');
INSERT INTO django_migrations VALUES(25,'journalapp','0007_archivedjournal_featured','2025-03-30 23:16:19.254145');
CREATE TABLE IF NOT EXISTS "django_content_type" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "app_label" varchar(100) NOT NULL, "model" varchar(100) NOT NULL);
INSERT INTO django_content_type VALUES(1,'admin','logentry');
INSERT INTO django_content_type VALUES(2,'auth','permission');
INSERT INTO django_content_type VALUES(3,'auth','group');
INSERT INTO django_content_type VALUES(4,'contenttypes','contenttype');
INSERT INTO django_content_type VALUES(5,'sessions','session');
INSERT INTO django_content_type VALUES(6,'journalapp','department');
INSERT INTO django_content_type VALUES(7,'journalapp','heroslide');
INSERT INTO django_content_type VALUES(8,'journalapp','sitesettings');
INSERT INTO django_content_type VALUES(9,'journalapp','customuser');
INSERT INTO django_content_type VALUES(10,'journalapp','comment');
INSERT INTO django_content_type VALUES(11,'journalapp','profile');
INSERT INTO django_content_type VALUES(12,'journalapp','review');
INSERT INTO django_content_type VALUES(13,'journalapp','article');
INSERT INTO django_content_type VALUES(14,'journalapp','articlecategory');
INSERT INTO django_content_type VALUES(15,'journalapp','archivedjournal');
CREATE TABLE IF NOT EXISTS "auth_group_permissions" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "group_id" integer NOT NULL REFERENCES "auth_group" ("id") DEFERRABLE INITIALLY DEFERRED, "permission_id" integer NOT NULL REFERENCES "auth_permission" ("id") DEFERRABLE INITIALLY DEFERRED);
CREATE TABLE IF NOT EXISTS "auth_permission" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "content_type_id" integer NOT NULL REFERENCES "django_content_type" ("id") DEFERRABLE INITIALLY DEFERRED, "codename" varchar(100) NOT NULL, "name" varchar(255) NOT NULL);
INSERT INTO auth_permission VALUES(1,1,'add_logentry','Can add log entry');
INSERT INTO auth_permission VALUES(2,1,'change_logentry','Can change log entry');
INSERT INTO auth_permission VALUES(3,1,'delete_logentry','Can delete log entry');
INSERT INTO auth_permission VALUES(4,1,'view_logentry','Can view log entry');
INSERT INTO auth_permission VALUES(5,2,'add_permission','Can add permission');
INSERT INTO auth_permission VALUES(6,2,'change_permission','Can change permission');
INSERT INTO auth_permission VALUES(7,2,'delete_permission','Can delete permission');
INSERT INTO auth_permission VALUES(8,2,'view_permission','Can view permission');
INSERT INTO auth_permission VALUES(9,3,'add_group','Can add group');
INSERT INTO auth_permission VALUES(10,3,'change_group','Can change group');
INSERT INTO auth_permission VALUES(11,3,'delete_group','Can delete group');
INSERT INTO auth_permission VALUES(12,3,'view_group','Can view group');
INSERT INTO auth_permission VALUES(13,4,'add_contenttype','Can add content type');
INSERT INTO auth_permission VALUES(14,4,'change_contenttype','Can change content type');
INSERT INTO auth_permission VALUES(15,4,'delete_contenttype','Can delete content type');
INSERT INTO auth_permission VALUES(16,4,'view_contenttype','Can view content type');
INSERT INTO auth_permission VALUES(17,5,'add_session','Can add session');
INSERT INTO auth_permission VALUES(18,5,'change_session','Can change session');
INSERT INTO auth_permission VALUES(19,5,'delete_session','Can delete session');
INSERT INTO auth_permission VALUES(20,5,'view_session','Can view session');
INSERT INTO auth_permission VALUES(21,6,'add_department','Can add department');
INSERT INTO auth_permission VALUES(22,6,'change_department','Can change department');
INSERT INTO auth_permission VALUES(23,6,'delete_department','Can delete department');
INSERT INTO auth_permission VALUES(24,6,'view_department','Can view department');
INSERT INTO auth_permission VALUES(25,7,'add_heroslide','Can add hero slide');
INSERT INTO auth_permission VALUES(26,7,'change_heroslide','Can change hero slide');
INSERT INTO auth_permission VALUES(27,7,'delete_heroslide','Can delete hero slide');
INSERT INTO auth_permission VALUES(28,7,'view_heroslide','Can view hero slide');
INSERT INTO auth_permission VALUES(29,8,'add_sitesettings','Can add Site Settings');
INSERT INTO auth_permission VALUES(30,8,'change_sitesettings','Can change Site Settings');
INSERT INTO auth_permission VALUES(31,8,'delete_sitesettings','Can delete Site Settings');
INSERT INTO auth_permission VALUES(32,8,'view_sitesettings','Can view Site Settings');
INSERT INTO auth_permission VALUES(33,9,'add_customuser','Can add customuser');
INSERT INTO auth_permission VALUES(34,9,'change_customuser','Can change customuser');
INSERT INTO auth_permission VALUES(35,9,'delete_customuser','Can delete customuser');
INSERT INTO auth_permission VALUES(36,9,'view_customuser','Can view customuser');
INSERT INTO auth_permission VALUES(37,10,'add_comment','Can add comment');
INSERT INTO auth_permission VALUES(38,10,'change_comment','Can change comment');
INSERT INTO auth_permission VALUES(39,10,'delete_comment','Can delete comment');
INSERT INTO auth_permission VALUES(40,10,'view_comment','Can view comment');
INSERT INTO auth_permission VALUES(41,11,'add_profile','Can add profile');
INSERT INTO auth_permission VALUES(42,11,'change_profile','Can change profile');
INSERT INTO auth_permission VALUES(43,11,'delete_profile','Can delete profile');
INSERT INTO auth_permission VALUES(44,11,'view_profile','Can view profile');
INSERT INTO auth_permission VALUES(45,12,'add_review','Can add review');
INSERT INTO auth_permission VALUES(46,12,'change_review','Can change review');
INSERT INTO auth_permission VALUES(47,12,'delete_review','Can delete review');
INSERT INTO auth_permission VALUES(48,12,'view_review','Can view review');
INSERT INTO auth_permission VALUES(49,13,'add_article','Can add article');
INSERT INTO auth_permission VALUES(50,13,'change_article','Can change article');
INSERT INTO auth_permission VALUES(51,13,'delete_article','Can delete article');
INSERT INTO auth_permission VALUES(52,13,'view_article','Can view article');
INSERT INTO auth_permission VALUES(53,14,'add_articlecategory','Can add article category');
INSERT INTO auth_permission VALUES(54,14,'change_articlecategory','Can change article category');
INSERT INTO auth_permission VALUES(55,14,'delete_articlecategory','Can delete article category');
INSERT INTO auth_permission VALUES(56,14,'view_articlecategory','Can view article category');
INSERT INTO auth_permission VALUES(57,15,'add_archivedjournal','Can add archived journal');
INSERT INTO auth_permission VALUES(58,15,'change_archivedjournal','Can change archived journal');
INSERT INTO auth_permission VALUES(59,15,'delete_archivedjournal','Can delete archived journal');
INSERT INTO auth_permission VALUES(60,15,'view_archivedjournal','Can view archived journal');
CREATE TABLE IF NOT EXISTS "auth_group" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "name" varchar(150) NOT NULL UNIQUE);
CREATE TABLE IF NOT EXISTS "journalapp_heroslide" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "title" varchar(200) NOT NULL, "subtitle" varchar(300) NOT NULL, "image" varchar(100) NOT NULL, "button_text" varchar(50) NOT NULL, "button_url" varchar(200) NOT NULL, "order" integer unsigned NOT NULL CHECK ("order" >= 0), "is_active" bool NOT NULL);
INSERT INTO journalapp_heroslide VALUES(1,'Welcome to Jos  Journal of English Language & Humanities','A platform for publishing and accessing academic journals.','hero_slides/pla.jpg','Learn More','#',1,1);
CREATE TABLE IF NOT EXISTS "journalapp_sitesettings" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "site_title" varchar(100) NOT NULL, "site_description" text NOT NULL, "logo" varchar(100) NULL, "favicon" varchar(100) NULL, "primary_color" varchar(20) NOT NULL, "secondary_color" varchar(20) NOT NULL, "footer_text" text NOT NULL, "contact_email" varchar(254) NOT NULL, "contact_phone" varchar(20) NOT NULL, "facebook_url" varchar(200) NOT NULL, "twitter_url" varchar(200) NOT NULL, "instagram_url" varchar(200) NOT NULL, "linkedin_url" varchar(200) NOT NULL);
INSERT INTO journalapp_sitesettings VALUES(1,'Jos Journal of English & Humanities','','','','#007bff','#6c757d','© University of Jos Journal System','contact@unijosjournals.edu.ng','','','','','');
CREATE TABLE IF NOT EXISTS "journalapp_customuser" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "password" varchar(128) NOT NULL, "last_login" datetime NULL, "is_superuser" bool NOT NULL, "email" varchar(254) NOT NULL UNIQUE, "first_name" varchar(30) NOT NULL, "last_name" varchar(30) NOT NULL, "is_active" bool NOT NULL, "is_staff" bool NOT NULL, "date_joined" datetime NOT NULL);
INSERT INTO journalapp_customuser VALUES(1,'pbkdf2_sha256$870000$bWLDoIFNyPIb35xDWwaKtz$D8H7h/I9JuOblt3z77d1Qdnvpbcz5dhmIoZ/8Qx7/1M=','2025-11-09 21:12:59.556778',1,'onahjonah@gmail.com','Jonah','Onah',1,1,'2025-03-27 18:29:33.009194');
INSERT INTO journalapp_customuser VALUES(2,'pbkdf2_sha256$870000$fWXlfh951zNO5yter4vtVP$BZoZ8cBcL5TQlfFVeO9hWrnSe0AdBw/6U3ZIFJ8J/k4=','2025-03-28 01:44:35.825272',0,'ruchina09@gmail.com','Ruth','Goodness',1,0,'2025-03-27 23:08:55.138172');
INSERT INTO journalapp_customuser VALUES(3,'pbkdf2_sha256$870000$PnxmUaxZlMERryqetJE9YJ$+6KMlnT4rPdn99lLT3zaOxLT98S40ZgxzSna9y8oRyI=','2025-06-04 08:38:47.894014',0,'mailonahjonah@gmail.com','John','Jonah',1,0,'2025-03-27 23:15:25.975192');
CREATE TABLE IF NOT EXISTS "journalapp_customuser_groups" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "customuser_id" bigint NOT NULL REFERENCES "journalapp_customuser" ("id") DEFERRABLE INITIALLY DEFERRED, "group_id" integer NOT NULL REFERENCES "auth_group" ("id") DEFERRABLE INITIALLY DEFERRED);
CREATE TABLE IF NOT EXISTS "journalapp_customuser_user_permissions" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "customuser_id" bigint NOT NULL REFERENCES "journalapp_customuser" ("id") DEFERRABLE INITIALLY DEFERRED, "permission_id" integer NOT NULL REFERENCES "auth_permission" ("id") DEFERRABLE INITIALLY DEFERRED);
CREATE TABLE IF NOT EXISTS "django_admin_log" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "object_id" text NULL, "object_repr" varchar(200) NOT NULL, "action_flag" smallint unsigned NOT NULL CHECK ("action_flag" >= 0), "change_message" text NOT NULL, "content_type_id" integer NULL REFERENCES "django_content_type" ("id") DEFERRABLE INITIALLY DEFERRED, "user_id" bigint NOT NULL REFERENCES "journalapp_customuser" ("id") DEFERRABLE INITIALLY DEFERRED, "action_time" datetime NOT NULL);
INSERT INTO django_admin_log VALUES(1,'1','Department of English Language',1,'[{"added": {}}]',6,1,'2025-03-27 22:14:19.346576');
INSERT INTO django_admin_log VALUES(2,'1','Welcome to University of Jos English Language Journal',1,'[{"added": {}}]',7,1,'2025-03-27 22:29:50.019723');
INSERT INTO django_admin_log VALUES(3,'2','Department of General Studies',1,'[{"added": {}}]',6,1,'2025-03-27 22:55:19.639287');
INSERT INTO django_admin_log VALUES(4,'2','ruchina09@gmail.com''s Profile',2,'[{"changed": {"fields": ["Department"]}}]',11,1,'2025-03-27 23:30:55.410911');
INSERT INTO django_admin_log VALUES(5,'1','Uncategorized',1,'[{"added": {}}]',14,1,'2025-03-28 00:09:07.139293');
INSERT INTO django_admin_log VALUES(6,'1','Empowering African Youth Through HackathonAfrica: A Model for Bridging the Tech Skills Gap',2,'[{"changed": {"fields": ["Status", "Published at"]}}]',13,1,'2025-03-28 00:52:00.823730');
INSERT INTO django_admin_log VALUES(7,'1','Empowering African Youth Through HackathonAfrica: A Model for Bridging the Tech Skills Gap',2,'[{"changed": {"fields": ["Status"]}}]',13,1,'2025-03-28 00:55:27.886377');
INSERT INTO django_admin_log VALUES(8,'2','Voluptatibus voluptatem repellendus Ex ad aut sequi in excepteur omnis praesentium fugiat blanditiis voluptates dolor excepturi voluptas esse aut consequatur',2,'[{"changed": {"fields": ["Status"]}}]',13,1,'2025-03-29 20:27:23.029731');
INSERT INTO django_admin_log VALUES(9,'2','Voluptatibus voluptatem repellendus Ex ad aut sequi in excepteur omnis praesentium fugiat blanditiis voluptates dolor excepturi voluptas esse aut consequatur',2,'[{"changed": {"fields": ["Status"]}}]',13,1,'2025-03-29 20:27:53.435580');
INSERT INTO django_admin_log VALUES(10,'2','Voluptatibus voluptatem repellendus Ex ad aut sequi in excepteur omnis praesentium fugiat blanditiis voluptates dolor excepturi voluptas esse aut consequatur',2,'[{"changed": {"fields": ["Status"]}}]',13,1,'2025-03-29 20:33:38.925931');
INSERT INTO django_admin_log VALUES(11,'2','Voluptatibus voluptatem repellendus Ex ad aut sequi in excepteur omnis praesentium fugiat blanditiis voluptates dolor excepturi voluptas esse aut consequatur',2,'[{"changed": {"fields": ["Status"]}}]',13,1,'2025-03-29 20:34:08.068678');
INSERT INTO django_admin_log VALUES(12,'2','Voluptatibus voluptatem repellendus Ex ad aut sequi in excepteur omnis praesentium fugiat blanditiis voluptates dolor excepturi voluptas esse aut consequatur',2,'[{"changed": {"fields": ["Status"]}}]',13,1,'2025-03-29 20:34:26.000391');
INSERT INTO django_admin_log VALUES(13,'1','Welcome to Jos  Journal of English Language & Humanities',2,'[{"changed": {"fields": ["Title", "Subtitle"]}}]',7,1,'2025-03-30 20:36:04.838044');
INSERT INTO django_admin_log VALUES(14,'1','Site Settings',2,'[{"changed": {"fields": ["Site title"]}}]',8,1,'2025-03-30 21:16:44.163537');
INSERT INTO django_admin_log VALUES(15,'2','Voluptatibus voluptatem repellendus Ex ad aut sequi in excepteur omnis praesentium fugiat blanditiis voluptates dolor excepturi voluptas esse aut consequatur',2,'[{"changed": {"fields": ["Status"]}}]',13,1,'2025-03-30 21:28:57.782316');
INSERT INTO django_admin_log VALUES(16,'2','Voluptatibus voluptatem repellendus Ex ad aut sequi in excepteur omnis praesentium fugiat blanditiis voluptates dolor excepturi voluptas esse aut consequatur',2,'[{"changed": {"fields": ["File"]}}]',13,1,'2025-03-30 21:54:39.844964');
INSERT INTO django_admin_log VALUES(17,'2','Voluptatibus voluptatem repellendus Ex ad aut sequi in excepteur omnis praesentium fugiat blanditiis voluptates dolor excepturi voluptas esse aut consequatur',2,'[{"changed": {"fields": ["Status"]}}]',13,1,'2025-03-30 21:55:56.241665');
INSERT INTO django_admin_log VALUES(18,'2','Voluptatibus voluptatem repellendus Ex ad aut sequi in excepteur omnis praesentium fugiat blanditiis voluptates dolor excepturi voluptas esse aut consequatur',2,'[{"changed": {"fields": ["Revised document"]}}]',13,1,'2025-03-30 22:30:28.964548');
CREATE TABLE IF NOT EXISTS "django_session" ("session_key" varchar(40) NOT NULL PRIMARY KEY, "session_data" text NOT NULL, "expire_date" datetime NOT NULL);
INSERT INTO django_session VALUES('c8foebl5az6mbjf5wcjsqa7iyko6vro7','.eJxVjEEOgjAQRe_StWmAFlpYuvcMzXRmKlXTEgqJxnh3IWGh2__ef2_hYF1GtxaeXSQxiFqcfjcPeOe0A7pBumaJOS1z9HJX5EGLvGTix_lw_wIjlHF7a2Rb9z4EpRurup6CaRWD1nVAY8AzkvWhbwx20FJLZKnxAUhBhbCRPVq4lJiT4-cU55cYqs8Xz5dAzA:1txxxr:bO9uBHG3JbD8gxw-u4LJLmE_4ZpFfNtapcYOxzNqWCw','2025-04-11 00:52:51.222237');
INSERT INTO django_session VALUES('d418gmawwq329m95gnfufu9qnd2c4zq7','.eJxVjMsOwiAQRf-FtSETKC-X7v0GMsOAVA0kpV0Z_12bdKHbe865LxFxW2vcRl7izOIslDj9boTpkdsO-I7t1mXqbV1mkrsiDzrktXN-Xg7376DiqN_aF0XBJG-sA8sBNQGCycVzsWaaGKzLmiEAZUdgCKDQpFVh7Z23GsX7A93aN6Y:1txylv:uxZUZOfsY56iR0n1pL01EvJqLRIb3aUVJyAG3ULR2Mc','2025-04-11 01:44:35.830151');
INSERT INTO django_session VALUES('z5n2wvde3lb5u6ob6yb3z1zshizqwfhx','.eJxVjDsOwjAQBe_iGlnxev2jpOcMlj9rHEC2FCcV4u4QKQW0b2bei_mwrdVvgxY_Z3Zmgp1-txjSg9oO8j20W-ept3WZI98VftDBrz3T83K4fwc1jPqtnUCDwZEsmrQBa3UmkhEdJIFOQkEtQE0WJp0KQXAykkwqK9RFghHs_QHCNTbz:1tyzMz:fB5mTdCdOrYv0S_1wauIIMiCMRucSYo_SonBwRsAkYA','2025-04-13 20:35:01.656555');
INSERT INTO django_session VALUES('w9fi1vga5sk3pgg1guymupps20pxj9g8','.eJxVjEEOwiAQRe_C2pAOhRZcuvcMZGYYpGpoUtqV8e7apAvd_vfef6mI21ri1mSJU1JnBer0uxHyQ-oO0h3rbdY813WZSO-KPmjT1znJ83K4fwcFW_nWNpi-k8Qme2DsechEydhgR6DOUEJBYA-UgxjrvXMgDgKPLgzOWPTq_QHyizfQ:1vICbn:-AVuUOb9isuojlLsRt1RcldPx-dxByeeaf_q1yk3B5w','2025-11-23 21:05:59.416138');
INSERT INTO django_session VALUES('slolf4mtlx845assqvmrb4s51nvl1886','.eJxVjEEOwiAQRe_C2pAOhRZcuvcMZGYYpGpoUtqV8e7apAvd_vfef6mI21ri1mSJU1JnBer0uxHyQ-oO0h3rbdY813WZSO-KPmjT1znJ83K4fwcFW_nWNpi-k8Qme2DsechEydhgR6DOUEJBYA-UgxjrvXMgDgKPLgzOWPTq_QHyizfQ:1vICiZ:fX8xgUt55qV_xokBaSTopinpWy_4DoHwBBETTbUdips','2025-11-23 21:12:59.559672');
CREATE TABLE IF NOT EXISTS "journalapp_articlecategory" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "name" varchar(100) NOT NULL, "description" text NOT NULL, "is_default" bool NOT NULL);
INSERT INTO journalapp_articlecategory VALUES(1,'Uncategorized','',1);
CREATE TABLE IF NOT EXISTS "journalapp_department" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "name" varchar(100) NOT NULL, "code" varchar(10) NOT NULL UNIQUE, "description" text NOT NULL, "cover_image" varchar(100) NULL, "journal_title" varchar(200) NOT NULL, "journal_description" text NOT NULL);
INSERT INTO journalapp_department VALUES(1,'Department of English Language','001','Department of English Language, University of Jos','','UJ English Journal','this is the Journal for the English Language Department');
INSERT INTO journalapp_department VALUES(2,'Department of General Studies','002','Department of General Studies, University of Jos','','GST Journal','Journal of General Studies');
CREATE TABLE IF NOT EXISTS "journalapp_profile" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "profile_picture" varchar(100) NULL, "is_editor" bool NOT NULL, "is_reviewer" bool NOT NULL, "department_id" bigint NULL REFERENCES "journalapp_department" ("id") DEFERRABLE INITIALLY DEFERRED, "user_id" bigint NOT NULL UNIQUE REFERENCES "journalapp_customuser" ("id") DEFERRABLE INITIALLY DEFERRED, "bio" text NOT NULL);
INSERT INTO journalapp_profile VALUES(1,'profile_pics/onah4jc_1739371412408.jpeg',0,0,1,1,'');
INSERT INTO journalapp_profile VALUES(2,'',0,0,2,2,'');
INSERT INTO journalapp_profile VALUES(3,'profile_pics/onahjonah.png',0,0,1,3,'');
CREATE TABLE IF NOT EXISTS "journalapp_review" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "comments" text NOT NULL, "created_at" datetime NOT NULL, "updated_at" datetime NOT NULL, "reviewer_id" bigint NOT NULL REFERENCES "journalapp_customuser" ("id") DEFERRABLE INITIALLY DEFERRED, "article_id" bigint NOT NULL REFERENCES "journalapp_article" ("id") DEFERRABLE INITIALLY DEFERRED, "decision" varchar(20) NOT NULL);
CREATE TABLE IF NOT EXISTS "journalapp_article" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "title" varchar(200) NOT NULL, "abstract" text NOT NULL, "content" text NOT NULL, "file" varchar(100) NULL, "status" varchar(20) NOT NULL, "created_at" datetime NOT NULL, "updated_at" datetime NOT NULL, "published_at" datetime NULL, "author_id" bigint NOT NULL REFERENCES "journalapp_customuser" ("id") DEFERRABLE INITIALLY DEFERRED, "department_id" bigint NOT NULL REFERENCES "journalapp_department" ("id") DEFERRABLE INITIALLY DEFERRED, "category_id" bigint NOT NULL REFERENCES "journalapp_articlecategory" ("id") DEFERRABLE INITIALLY DEFERRED, "keywords" varchar(255) NOT NULL, "revised_document" varchar(100) NULL, "revision_notes" text NULL);
INSERT INTO journalapp_article VALUES(1,'Empowering African Youth Through HackathonAfrica: A Model for Bridging the Tech Skills Gap','<p>HackathonAfrica is a pioneering initiative designed to equip young Africans with in-demand technical skills through an immersive and structured learning experience. This paper examines the impact of HackathonAfrica on youth empowerment, employment, and innovation. We outline our approach, methodologies, key successes, and challenges faced in implementing the program across various regions. The findings highlight the effectiveness of project-based learning, mentorship, and strategic industry partnerships in bridging the tech skills gap and fostering a sustainable pipeline of African technology talent.</p>',unistr('<p><strong>1. Introduction</strong> The global demand for technology professionals is rapidly increasing, yet Africa faces a significant skills gap in this sector. Many young Africans possess the drive and talent to succeed in tech but lack access to quality training and industry exposure. HackathonAfrica was founded to address this gap by providing hands-on learning, mentorship, and real-world project experience. This paper discusses our framework, outcomes, and the broader implications of our work.</p>\u000d\u000a\u000d\u000a<p><strong>2. Program Structure and Methodology</strong> HackathonAfrica follows a structured yet flexible model to accommodate diverse learners. Our approach includes:</p>\u000d\u000a\u000d\u000a<ul>\u000d\u000a\u0009<li>\u000d\u000a\u0009<p><strong>Bootcamp Training:</strong> Intensive coding and problem-solving sessions focused on web development, backend systems, UI/UX, cybersecurity, and digital marketing.</p>\u000d\u000a\u0009</li>\u000d\u000a\u0009<li>\u000d\u000a\u0009<p><strong>Mentorship &amp; Industry Exposure:</strong> Pairing participants with experienced tech professionals to guide them through practical projects and career navigation.</p>\u000d\u000a\u0009</li>\u000d\u000a\u0009<li>\u000d\u000a\u0009<p><strong>Project-Based Learning:</strong> Engaging participants in real-world projects that mirror industry challenges, fostering creativity, collaboration, and problem-solving skills.</p>\u000d\u000a\u0009</li>\u000d\u000a\u0009<li>\u000d\u000a\u0009<p><strong>Internship &amp; Placement Support:</strong> Connecting graduates with companies and startups seeking tech talent.</p>\u000d\u000a\u0009</li>\u000d\u000a</ul>\u000d\u000a\u000d\u000a<p><strong>3. Impact and Success Stories</strong> Since its inception, HackathonAfrica has trained hundreds of young individuals, many of whom have secured employment, launched startups, or contributed to open-source projects. Notable achievements include:</p>\u000d\u000a\u000d\u000a<ul>\u000d\u000a\u0009<li>\u000d\u000a\u0009<p>Placement of graduates in reputable tech firms.</p>\u000d\u000a\u0009</li>\u000d\u000a\u0009<li>\u000d\u000a\u0009<p>Development of innovative digital solutions addressing local challenges.</p>\u000d\u000a\u0009</li>\u000d\u000a\u0009<li>\u000d\u000a\u0009<p>Strengthened collaboration between African startups and emerging tech talent.</p>\u000d\u000a\u0009</li>\u000d\u000a</ul>\u000d\u000a\u000d\u000a<p><strong>4. Challenges and Lessons Learned</strong> Despite its success, HackathonAfrica faces challenges such as:</p>\u000d\u000a\u000d\u000a<ul>\u000d\u000a\u0009<li>\u000d\u000a\u0009<p>Limited funding for scaling operations.</p>\u000d\u000a\u0009</li>\u000d\u000a\u0009<li>\u000d\u000a\u0009<p>Internet and infrastructure constraints in rural regions.</p>\u000d\u000a\u0009</li>\u000d\u000a\u0009<li>\u000d\u000a\u0009<p>Ensuring long-term engagement and career growth for participants post-training. Lessons from our experience emphasize the importance of strategic partnerships, continuous curriculum adaptation, and robust alumni networks.</p>\u000d\u000a\u0009</li>\u000d\u000a</ul>\u000d\u000a\u000d\u000a<p><strong>5. Conclusion and Future Outlook</strong> HackathonAfrica represents a scalable model for tech education in Africa. Moving forward, we aim to expand our reach, deepen industry collaborations, and integrate AI and emerging technologies into our curriculum. By fostering an inclusive and innovative ecosystem, we envision a future where African youth are at the forefront of the global digital economy.</p>'),'','published','2025-03-28 00:30:17.259238','2025-03-28 00:55:27.885104','2025-03-28 00:51:54',1,1,1,'HackathonAfrica, technology skills gap, youth empowerment, project-based learning, African tech ecosystem',NULL,NULL);
INSERT INTO journalapp_article VALUES(2,'Voluptatibus voluptatem repellendus Ex ad aut sequi in excepteur omnis praesentium fugiat blanditiis voluptates dolor excepturi voluptas esse aut consequatur','<p>&nbsp;kdjf;kjd;sdglskdlks;ldg;ksjdkgsdfnfalkjdkalsfdj;JSLKlKDL;</p>','<p>dsu;odifsodfposidofis[odifs[odif[sopdfpsdf</p>','journal_files/AKILIMO_Survey_2024_tcNKuS2.docx','revision_required','2025-03-29 20:25:15.885081','2025-03-30 22:30:28.963464',NULL,1,1,1,'Incidunt vel delectus impedit vel illum dolor quo et voluptatem sed est in quia','revised_documents/AKILIMO_Survey_2024_tcNKuS2.docx','');
CREATE TABLE IF NOT EXISTS "journalapp_comment" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "created_at" datetime NOT NULL, "author_id" bigint NOT NULL REFERENCES "journalapp_customuser" ("id") DEFERRABLE INITIALLY DEFERRED, "article_id" bigint NOT NULL REFERENCES "journalapp_article" ("id") DEFERRABLE INITIALLY DEFERRED, "content" text NOT NULL);
CREATE TABLE IF NOT EXISTS "journalapp_archivedjournal" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "title" varchar(255) NOT NULL, "description" text NULL, "volume" varchar(50) NULL, "issue" varchar(50) NULL, "publication_date" date NOT NULL, "document" varchar(100) NOT NULL, "cover_image" varchar(100) NULL, "uploaded_at" datetime NOT NULL, "department_id" bigint NOT NULL REFERENCES "journalapp_department" ("id") DEFERRABLE INITIALLY DEFERRED, "uploaded_by_id" bigint NULL REFERENCES "journalapp_customuser" ("id") DEFERRABLE INITIALLY DEFERRED, "featured" bool NOT NULL);
INSERT INTO sqlite_sequence VALUES('django_migrations',25);
INSERT INTO sqlite_sequence VALUES('django_content_type',15);
INSERT INTO sqlite_sequence VALUES('auth_permission',60);
INSERT INTO sqlite_sequence VALUES('auth_group',0);
INSERT INTO sqlite_sequence VALUES('django_admin_log',18);
INSERT INTO sqlite_sequence VALUES('journalapp_customuser',3);
INSERT INTO sqlite_sequence VALUES('journalapp_sitesettings',1);
INSERT INTO sqlite_sequence VALUES('journalapp_heroslide',1);
INSERT INTO sqlite_sequence VALUES('journalapp_articlecategory',1);
INSERT INTO sqlite_sequence VALUES('journalapp_department',2);
INSERT INTO sqlite_sequence VALUES('journalapp_profile',3);
INSERT INTO sqlite_sequence VALUES('journalapp_review',0);
INSERT INTO sqlite_sequence VALUES('journalapp_article',2);
INSERT INTO sqlite_sequence VALUES('journalapp_comment',0);
INSERT INTO sqlite_sequence VALUES('journalapp_archivedjournal',0);
CREATE UNIQUE INDEX "django_content_type_app_label_model_76bd3d3b_uniq" ON "django_content_type" ("app_label", "model");
CREATE UNIQUE INDEX "auth_group_permissions_group_id_permission_id_0cd325b0_uniq" ON "auth_group_permissions" ("group_id", "permission_id");
CREATE INDEX "auth_group_permissions_group_id_b120cbf9" ON "auth_group_permissions" ("group_id");
CREATE INDEX "auth_group_permissions_permission_id_84c5c92e" ON "auth_group_permissions" ("permission_id");
CREATE UNIQUE INDEX "auth_permission_content_type_id_codename_01ab375a_uniq" ON "auth_permission" ("content_type_id", "codename");
CREATE INDEX "auth_permission_content_type_id_2f476e4b" ON "auth_permission" ("content_type_id");
CREATE UNIQUE INDEX "journalapp_customuser_groups_customuser_id_group_id_697b6dce_uniq" ON "journalapp_customuser_groups" ("customuser_id", "group_id");
CREATE INDEX "journalapp_customuser_groups_customuser_id_43be4c84" ON "journalapp_customuser_groups" ("customuser_id");
CREATE INDEX "journalapp_customuser_groups_group_id_b6f53d6d" ON "journalapp_customuser_groups" ("group_id");
CREATE UNIQUE INDEX "journalapp_customuser_user_permissions_customuser_id_permission_id_36c1a266_uniq" ON "journalapp_customuser_user_permissions" ("customuser_id", "permission_id");
CREATE INDEX "journalapp_customuser_user_permissions_customuser_id_c566ce4f" ON "journalapp_customuser_user_permissions" ("customuser_id");
CREATE INDEX "journalapp_customuser_user_permissions_permission_id_afe8b30a" ON "journalapp_customuser_user_permissions" ("permission_id");
CREATE INDEX "django_admin_log_content_type_id_c4bce8eb" ON "django_admin_log" ("content_type_id");
CREATE INDEX "django_admin_log_user_id_c564eba6" ON "django_admin_log" ("user_id");
CREATE INDEX "django_session_expire_date_a5c62663" ON "django_session" ("expire_date");
CREATE INDEX "journalapp_profile_department_id_ec2c66c8" ON "journalapp_profile" ("department_id");
CREATE INDEX "journalapp_review_reviewer_id_26d8f7fc" ON "journalapp_review" ("reviewer_id");
CREATE INDEX "journalapp_review_article_id_a4b3f5b1" ON "journalapp_review" ("article_id");
CREATE INDEX "journalapp_article_author_id_98e8b8aa" ON "journalapp_article" ("author_id");
CREATE INDEX "journalapp_article_department_id_d93e0865" ON "journalapp_article" ("department_id");
CREATE INDEX "journalapp_article_category_id_961cd959" ON "journalapp_article" ("category_id");
CREATE INDEX "journalapp_comment_author_id_dde9e1e8" ON "journalapp_comment" ("author_id");
CREATE INDEX "journalapp_comment_article_id_6fe7ea67" ON "journalapp_comment" ("article_id");
CREATE INDEX "journalapp_archivedjournal_department_id_ec1172c1" ON "journalapp_archivedjournal" ("department_id");
CREATE INDEX "journalapp_archivedjournal_uploaded_by_id_d4e51e16" ON "journalapp_archivedjournal" ("uploaded_by_id");
COMMIT;
