# Generated by Django 5.1.7 on 2025-11-22 13:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journalapp', '0002_articlelog'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='doi',
            field=models.CharField(blank=True, help_text='Digital Object Identifier', max_length=100),
        ),
        migrations.AddField(
            model_name='article',
            name='extracted_citations',
            field=models.TextField(blank=True, help_text='References/citations extracted from the document'),
        ),
        migrations.AddField(
            model_name='article',
            name='extracted_sections',
            field=models.JSONField(blank=True, default=list, help_text='Structured sections extracted from the document'),
        ),
        migrations.AddField(
            model_name='article',
            name='final_document',
            field=models.FileField(blank=True, help_text='The final approved Word document', null=True, upload_to='final_documents/'),
        ),
        migrations.AddField(
            model_name='article',
            name='issue',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='article',
            name='page_end',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='article',
            name='page_start',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='article',
            name='volume',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Preliminary title of the article', max_length=300)),
                ('document', models.FileField(help_text='Upload your article in Word document format (.docx)', upload_to='submissions/')),
                ('cover_letter', models.TextField(blank=True, help_text='Optional cover letter or notes for the editor')),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('in_review', 'In Review'), ('with_editor', 'With Editor'), ('revision_requested', 'Revision Requested'), ('revised', 'Revised'), ('approved', 'Approved'), ('published', 'Published'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to=settings.AUTH_USER_MODEL)),
                ('journal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='journalapp.journal')),
                ('published_article', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_submission', to='journalapp.article')),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('reviewer', 'Reviewer'), ('editor', 'Editor')], max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('declined', 'Declined')], default='active', max_length=20)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, help_text='Notes about this assignment')),
                ('feedback', models.TextField(blank=True, help_text='Feedback from reviewer/editor')),
                ('recommendation', models.CharField(blank=True, choices=[('approve', 'Approve for Publication'), ('minor_revision', 'Minor Revisions Needed'), ('major_revision', 'Major Revisions Needed'), ('reject', 'Reject')], max_length=50)),
                ('assigned_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments_made', to=settings.AUTH_USER_MODEL)),
                ('assigned_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_submissions', to=settings.AUTH_USER_MODEL)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='journalapp.submission')),
            ],
            options={
                'ordering': ['-assigned_at'],
            },
        ),
        migrations.CreateModel(
            name='SubmissionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=255)),
                ('details', models.JSONField(blank=True, default=dict, help_text='Additional details about this action')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='journalapp.submission')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='SubmissionMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('attachment', models.FileField(blank=True, help_text='Optional file attachment', null=True, upload_to='chat_attachments/')),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recipient', models.ForeignKey(blank=True, help_text='Leave empty for group message', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_messages', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to=settings.AUTH_USER_MODEL)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='journalapp.submission')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumentVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(upload_to='submissions/versions/')),
                ('version_number', models.PositiveIntegerField()),
                ('notes', models.TextField(blank=True, help_text='Notes about this version')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('is_final', models.BooleanField(default=False, help_text='Mark as the final approved version')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_documents', to=settings.AUTH_USER_MODEL)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_versions', to='journalapp.submission')),
            ],
            options={
                'ordering': ['-version_number'],
                'unique_together': {('submission', 'version_number')},
            },
        ),
    ]
