# Generated by Django 5.1.7 on 2025-03-28 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journalapp', '0003_alter_articlecategory_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='keywords',
            field=models.CharField(blank=True, help_text='Enter keywords separated by commas', max_length=255),
        ),
    ]
