# Generated by Django 5.1.7 on 2025-11-22 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journalapp', '0003_submission_workflow'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='title',
            field=models.CharField(blank=True, help_text='Title will be extracted from final document', max_length=300),
        ),
    ]
