# Generated by Django 5.1.7 on 2025-03-30 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journalapp', '0004_article_keywords'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='revised_document',
            field=models.FileField(blank=True, null=True, upload_to='revised_documents/'),
        ),
        migrations.AddField(
            model_name='article',
            name='revision_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=models.TextField(),
        ),
    ]
