# Generated by Django 5.1.7 on 2025-11-22 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journalapp', '0004_remove_required_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='amended_document',
            field=models.FileField(blank=True, help_text="Amended document with reviewer's annotations and corrections", null=True, upload_to='amended_documents/'),
        ),
    ]
