# Generated by Django 5.1.7 on 2025-11-27 09:24

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


def populate_anonymized_identifiers(apps, schema_editor):
    """Populate anonymized_identifier for existing submissions"""
    Submission = apps.get_model('journalapp', 'Submission')

    # Get all submissions ordered by submission date
    submissions = Submission.objects.all().order_by('submitted_at')

    for submission in submissions:
        if not submission.anonymized_identifier:
            year = submission.submitted_at.year
            # Count submissions from that year before this one
            count = Submission.objects.filter(
                submitted_at__year=year,
                submitted_at__lt=submission.submitted_at
            ).count() + 1
            submission.anonymized_identifier = f"MS-{year}-{count:04d}"
            submission.save()


class Migration(migrations.Migration):

    dependencies = [
        ('journalapp', '0005_add_amended_document_to_assignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='access_token',
            field=models.CharField(blank=True, help_text='Unique access token for guest reviewers', max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='assignment',
            name='blinded',
            field=models.BooleanField(default=True, help_text='Whether author information should be hidden from reviewer'),
        ),
        migrations.AddField(
            model_name='submission',
            name='anonymized_identifier',
            field=models.CharField(blank=True, help_text='Auto-generated anonymous identifier for blind review', max_length=50),
        ),
        migrations.RunPython(populate_anonymized_identifiers),
        migrations.AlterField(
            model_name='submission',
            name='anonymized_identifier',
            field=models.CharField(blank=True, help_text='Auto-generated anonymous identifier for blind review', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='assigned_to',
            field=models.ForeignKey(blank=True, help_text='Regular user assigned to review', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_submissions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='GuestReviewer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('affiliation', models.CharField(blank=True, help_text='Institution or organization affiliation', max_length=300)),
                ('expertise_areas', models.TextField(blank=True, help_text='Areas of expertise (comma-separated)')),
                ('invitation_token', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique token for accessing the platform', unique=True)),
                ('token_expires_at', models.DateTimeField(blank=True, help_text='Token expiration date', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this guest reviewer can receive new assignments')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_guest_reviewers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='assignment',
            name='guest_reviewer',
            field=models.ForeignKey(blank=True, help_text='Guest reviewer assigned to review', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='journalapp.guestreviewer'),
        ),
    ]
