# Generated by Django 5.1.7 on 2025-03-30 23:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journalapp', '0005_article_revised_document_article_revision_notes_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchivedJournal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('volume', models.CharField(blank=True, max_length=50, null=True)),
                ('issue', models.CharField(blank=True, max_length=50, null=True)),
                ('publication_date', models.DateField()),
                ('document', models.FileField(upload_to='archived_journals/')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='archived_journal_covers/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archived_journals', to='journalapp.department')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-publication_date'],
            },
        ),
    ]
