# Generated by Django 5.1.7 on 2026-07-23 17:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journalapp', '0006_assignment_access_token_assignment_blinded_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='JournalRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', 'Journal Admin'), ('chief_editor', 'Chief Editor'), ('editor', 'Editor')], max_length=20)),
                ('granted_at', models.DateTimeField(auto_now_add=True)),
                ('granted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='journal_roles_granted', to=settings.AUTH_USER_MODEL)),
                ('journal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='journalapp.journal')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journal_roles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Journal Role',
                'verbose_name_plural': 'Journal Roles',
                'ordering': ['journal__name', 'role', 'user__email'],
                'unique_together': {('user', 'journal', 'role')},
            },
        ),
    ]
