# Generated by Django 5.1.7 on 2026-07-23 19:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journalapp', '0009_alter_journalrole_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChecklistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(help_text='The statement the author confirms.', max_length=500)),
                ('help_text', models.CharField(blank=True, help_text='Optional clarifying note shown under the item.', max_length=500)),
                ('order', models.PositiveIntegerField(default=0)),
                ('required', models.BooleanField(default=True, help_text='If ticked, the author cannot submit without confirming this item.')),
                ('is_active', models.BooleanField(default=True, help_text='Inactive items are hidden from new submissions but kept for history.')),
                ('journal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklist_items', to='journalapp.journal')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ChecklistResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_text', models.CharField(max_length=500)),
                ('checked', models.BooleanField(default=False)),
                ('responded_at', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='responses', to='journalapp.checklistitem')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklist_responses', to='journalapp.submission')),
            ],
            options={
                'ordering': ['item__order', 'item_id'],
                'unique_together': {('submission', 'item')},
            },
        ),
    ]
