# Generated by Django 5.1.7 on 2026-07-24 14:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journalapp', '0010_checklistitem_checklistresponse'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentversion',
            name='is_review_copy',
            field=models.BooleanField(default=False, help_text="A Chief-Editor-prepared, de-identified copy that reviewers download. Reviewers only ever see review copies, never the author's original upload."),
        ),
        migrations.AlterField(
            model_name='submission',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Review'), ('preparing', 'Preparing for Review'), ('in_review', 'In Review'), ('with_editor', 'With Editor'), ('revision_requested', 'Revision Requested'), ('revised', 'Revised'), ('approved', 'Approved'), ('published', 'Published'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
        migrations.CreateModel(
            name='ReviewRound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField()),
                ('opened_at', models.DateTimeField(auto_now_add=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('opened_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='review_rounds_opened', to=settings.AUTH_USER_MODEL)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_rounds', to='journalapp.submission')),
            ],
            options={
                'ordering': ['submission', 'number'],
                'unique_together': {('submission', 'number')},
            },
        ),
        migrations.AddField(
            model_name='assignment',
            name='review_round',
            field=models.ForeignKey(blank=True, help_text='Which review round this assignment belongs to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignments', to='journalapp.reviewround'),
        ),
    ]
