# Generated by Django 5.1.7 on 2026-07-24 14:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journalapp', '0011_documentversion_is_review_copy_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewerApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('affiliation', models.CharField(blank=True, help_text='Institution or organization', max_length=300)),
                ('position', models.CharField(blank=True, help_text='Role or title, e.g. Senior Lecturer', max_length=200)),
                ('qualifications', models.TextField(blank=True, help_text='Degrees, publications, relevant experience')),
                ('expertise_areas', models.TextField(blank=True, help_text='Areas of expertise (comma-separated)')),
                ('cv', models.FileField(blank=True, null=True, upload_to='reviewer_cvs/')),
                ('statement', models.TextField(blank=True, help_text='A short statement of interest')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewer_application', to=settings.AUTH_USER_MODEL)),
                ('guest_reviewer', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewer_application', to='journalapp.guestreviewer')),
                ('journals_of_interest', models.ManyToManyField(blank=True, related_name='reviewer_applications', to='journalapp.journal')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewer_applications_reviewed', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
