# Generated by Django 5.1.7 on 2026-07-24 19:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journalapp', '0012_reviewerapplication'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Review'), ('preparing', 'Preparing for Review'), ('in_review', 'In Review'), ('with_editor', 'With Editor'), ('revision_requested', 'Revision Requested'), ('revised', 'Revised'), ('approved', 'Approved'), ('awaiting_payment', 'Awaiting Payment'), ('published', 'Published'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
        migrations.CreateModel(
            name='JournalFee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default=0, help_text='Amount charged on acceptance, before publication.', max_digits=10)),
                ('currency', models.CharField(default='NGN', max_length=3)),
                ('is_active', models.BooleanField(default=True, help_text='Uncheck to publish this journal free of charge.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('journal', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fee', to='journalapp.journal')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='NGN', max_length=3)),
                ('reference', models.CharField(max_length=100, unique=True)),
                ('paystack_reference', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed'), ('waived', 'Waived')], default='pending', max_length=20)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('raw_response', models.JSONField(blank=True, default=dict)),
                ('waiver_reason', models.CharField(blank=True, max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to=settings.AUTH_USER_MODEL)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='journalapp.submission')),
                ('waived_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments_waived', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
